/**
 * Existing values in this map CANNOT be changed without
 * breaking existing MisinformationGame stored objects.
 * If a change is required, then a new version of the
 * compression should be created, so that compatibility
 * with old versions can be maintained.
 *
 * The aliases for the keys have been chosen in an
 * attempt to keep the most common keys as short as
 * possible, and to keep the aliases somewhat resembling
 * the original keys when possible.
 */
export const compressJsonKeyMap = {
    "id": "i",
    "headline": "h",
    "isTrue": "t",
    "changesToFollowers": "cf",
    "changesToCredibility": "cc",
    "numberOfReactions": "nr",
    "comments": "cm",
    "sourceName": "sn",
    "message": "m",
    "avatar": "a",
    "style": "y",
    "maxPosts": "x",
    "followers": "z",
    "credibility": "c",
    "truePostPercentage": "tpp",
    "like": "l",
    "likes": "ls",
    "dislike": "d",
    "dislikes": "ds",
    "share": "s",
    "shares": "ss",
    "flag": "f",
    "flags": "fs",
    "authorID": "aid",
    "authorName": "an",
    "name": "na",
    "description": "de",
    "lastModifiedTime": "lm",
    "enabled": "en",
    "prompt": "pr",
    "promptDelaySeconds": "pd",
    "length": "le",
    "requireReactions": "rr",
    "reactDelaySeconds": "rd",
    "requireComments": "rc",
    "minimumCommentLength": "mcl",
    "requireIdentification": "ri",
    "displayFollowers": "df",
    "displayCredibility": "dc",
    "displayProgress": "dp",
    "displayNumberOfReactions": "dn",
    "postEnabledReactions": "per",
    "commentEnabledReactions": "cer",
    "genCompletionCode": "gcc",
    "completionCodeDigits": "ccd",
    "genRandomDefaultAvatars": "rda",
    "preIntro": "pri",
    "preIntroDelaySeconds": "prid",
    "rules": "ru",
    "rulesDelaySeconds": "rud",
    "postIntro": "poi",
    "postIntroDelaySeconds": "poid",
    "debrief": "deb",
    "sourcePostSelectionMethod": "spsm",
    "sources": "o",
    "posts": "0",
    "sessionID": "si",
    "startTime": "st",
    "endTime": "et",
    "states": "sa",
    "participant": "pa",
    "participantID": "pi",
    "interactions": "is",
    "credibilityHistory": "ch",
    "followerHistory": "fh",
    "dismissedPrompt": "dip",
    "completionCode": "cco",
    "postShowTime": "e",
    "postReaction": "r",
    "commentReactions": "u",
    "comment": "n",
    "firstInteractTimeMS": "q",
    "lastInteractTimeMS": "w",
    "commentID": "k",
    "reaction": "g",
    "reactTimeMS": "j",
    "currentSource": "v",
    "currentPost": "b",
    "postID": "1",
    "shown": "2",
    "remainingUses": "3",
    "sourceID": "4",
    "studyID": "stid",
    "studyModTime": "stm",
    "type": "ty",
    "linearRelationship": "lr",
    "slope": "sl",
    "intercept": "in",
    "randomiseOrder": "ror",
    "order": "or"
};
